### ISSUE TITLE
Figuring Out Figure 4

### ISSUE THREAD

**Issue by Myfanwy** [Myfanwy/gst_rheo#2]
Hi @rmcelreath ,

Almost done, I promise.  I'm trying to visualize the results of m2NC (top-weighted model from Experiment 1).  Goal is to show that the model captures the bimodality of the raw data and also recreates the data-generating process of the experiments (makes good predictions).

Options are:

1: Simple comparison of model's implied predictions (across all treatments) and raw data:
![image](https://cloud.githubusercontent.com/assets/6519519/18144359/128499b6-6f7b-11e6-89c7-ba5e33f293da.png)

 -
 -

2. Option 2: Panel Plot with Raw Densities as Fig 4.a, Samples from the Posterior as Fig 4.b

![image](https://cloud.githubusercontent.com/assets/6519519/18144430/7f0cb956-6f7b-11e6-9a2f-337495ab136d.png)
![image](https://cloud.githubusercontent.com/assets/6519519/18144490/c264f18c-6f7b-11e6-891b-0b1a0e1e71bf.png)

Question: is it okay that this plot includes probabilities outside the bounds of the response variable (0, 1)?  I've cut the x-axis off at 0 and 1, but the tails are long - I assume it has something to do with the code that generates the curve, which adapted from Chapter 12 but may have done so inappropriately:

`for (i in 1:300) 
                curve(dnorm(x, logistic(post$b_above[i]), post$sigma_fish[i]), add = TRUE, col = col.alpha("black", 0.1))`

I took the logistic to visualize it on the proportional scale for easier comparison to the raw data.  Wasn't sure if I should take the logistic of `post$sigma_fish`, too, but when I tried it it completely flattened out the plot.

**Comment by rmcelreath** [comment]
To your plot bounds question, that's likely happening because of how density() works. If you tighten up the density kernel, it should help, but it'll make the density more jaggy. adj or adjust is the argument you want.

I don't understand you code snippet. Why dnorm? Each fish is not distribution normally. Rather the distribution of fish is normal (on the logit scale). I think you want dbeta2?

**Comment by Myfanwy** [comment]
Hi Richard,

Thanks so much!  I think I fixed it: 
![image](https://cloud.githubusercontent.com/assets/6519519/18298985/d3fcfd72-7471-11e6-80fa-9f78d38483b3.png)

The code is now:
    `post <- extract.samples(m2NC)`
        
    ## Fig 4.b: sample 300 trials from the posterior for each treatment
    plot(NULL, xlim = c(0, 1) , ylim = c(0, 5) ,
         xlab = "Proportion of Time Spent Positively Oriented", ylab = "Density")
    for (i in 1:300)
      curve( dbeta2(x, prob = logistic(post$b_above[i]), theta = post$theta[i]), add = TRUE,
             col = col.alpha("black", 0.1))
    for (i in 1:300)
      curve( dbeta2(x, prob = logistic(post$b_below[i]), theta = post$theta[i]), add = TRUE,
             col = col.alpha("brown", 0.1))
    for (i in 1:300)
      curve( dbeta2(x, prob = logistic(post$b_light[i]), theta = post$theta[i]), add = TRUE,
            col = col.alpha("dodgerblue", 0.1))
    for (i in 1:300)
      curve( dbeta2(x, prob = logistic(post$b_dark[i]), theta = post$theta[i]), add = TRUE,
             col = col.alpha("blue", 0.1))
    title('Repeated Posterior Sampling from m2NC by Treatment', add = TRUE)
    legend(0.8, 18, cex = 1, pt.cex = 1, c("Above", "Below", "Light", "Dark"), lty = c(1, 1,1,1), col =     c("brown", "black", "dodgerblue", "blue"), bty = "n")`

Unless you see any issues with this version of the plot, I'll send the complete draft of the manuscript along by the end of the week. 

Thanks again!

**Comment by rmcelreath** [comment]
Looks good, aside from the fact that I can't tell the blues apart. The black curves are hard to see, as well. But I do see them.

If I understand right, these curves are posterior samples for an average fish (since they neglect the random effects).

**Comment by Myfanwy** [comment]
Ok - changing the colors, and just want to make sure I have the code right before I finalize the figure: here's the code and plot for the fixed + random effects (I'll print out the structure of the model and the posterior so you can see what I'm pulling from):


    `> m2NC
    map2stan model fit
    9000 samples from 1 chain

    Formula:
    y ~ dbeta2(p, theta)
    logit(p) <- (b_above + ba_fish[fish_id])*above + (b_below + bb_fish[fish_id])*below 
    + (b_light +  bl_fish[fish_id])*light + (b_dark + bd_fish[fish_id])*dark

    c(ba_fish, bb_fish, bl_fish, bd_fish)[fish_id] ~ dmvnormNC(sigma_fish, Rho_fish)
    c(b_above, b_below, b_light, b_dark) ~ dnorm(0, 1)
    theta ~ dcauchy(0, 1)
    sigma_fish ~ dexp(1)
    Rho_fish ~ dlkjcorr(2)`

    `> str(post)
      List of 13
     $ theta      : num [1:9000(1d)] 17.6 8.4 10.5 10.2 15 ...
     $ z_N_fish_id: num [1:9000, 1:4, 1:23] -2.635 0.738 -1.4284 0.0166 1.1495 ...
     $ L_Rho_fish : num [1:9000, 1:4, 1:4] 1 1 1 1 1 1 1 1 1 1 ...
     $ b_above    : num [1:9000(1d)] -0.682 -0.928 -0.674 -0.737 -0.684 ...
     $ b_below    : num [1:9000(1d)] -0.625 -0.435 -0.479 -1.04 -0.668 ...
     $ b_light    : num [1:9000(1d)] -0.0476 0.2053 -0.1776 0.105 0.6702 ...
     $ b_dark     : num [1:9000(1d)] 0.935 0.436 0.556 0.264 0.645 ...
     $ sigma_fish : num [1:9000, 1:4] 0.0394 0.0687 0.1017 0.2747 0.101 ...
     $ ba_fish    : num [1:9000, 1:23] -0.10389 0.05072 -0.14529 0.00456 0.1161 ...
     $ bb_fish    : num [1:9000, 1:23] -0.1002 0.2044 -0.0782 0.2556 0.1891 ...
     $ bl_fish    : num [1:9000, 1:23] 2.1005 -0.0305 1.6669 2.345 0.0295 ...
     $ bd_fish    : num [1:9000, 1:23] 0.208 0.594 1.348 0.624 0.525 ...
     $ Rho_fish   : num [1:9000, 1:4, 1:4] 1 1 1 1 1 1 1 1 1 1 ...`


    `#plot
    plot(NULL, xlim = c(0, 1) , ylim = c(0, 12) ,
         xlab = "Proportion of Time Spent Positively Oriented", ylab = "Density")
    for (i in 1:300)
      curve( dbeta2(x, prob = logistic(post$b_above[i] + post$ba_fish[i]), theta = post$theta[i]), add = TRUE,  col = col.alpha("black", 0.2))
    for (i in 1:300)
      curve( dbeta2(x, prob = logistic(post$b_below[i] + post$bb_fish[i]), theta = post$theta[i]), add = TRUE, col = col.alpha("purple", 0.1))
    for (i in 1:300)
      curve( dbeta2(x, prob = logistic(post$b_light[i] + post$bl_fish[i]), theta = post$theta[i]), add = TRUE, col = col.alpha("dodgerblue", 0.2))
    for (i in 1:300)
      curve( dbeta2(x, prob = logistic(post$b_dark[i] + post$bd_fish[i]), theta = post$theta[i]), add = TRUE, col = col.alpha("orange", 0.15))`

![image](https://cloud.githubusercontent.com/assets/6519519/18320989/058de274-74e1-11e6-813b-11c700111395.png)


And for comparison, here's the plot for just the random effects - makes sense that the curves are  much less distinct, yes?

    `# just random effects:
    plot(NULL, xlim = c(0, 1) , ylim = c(0, 15) ,
         xlab = "Proportion of Time Spent Positively Oriented", ylab = "Density")
    for (i in 1:300)
      curve( dbeta2(x, prob = logistic(post$ba_fish[i]), theta = post$theta[i]), add = TRUE,
             col = col.alpha("black", 0.2))
    for (i in 1:300)
      curve( dbeta2(x, prob = logistic(post$bb_fish[i]), theta = post$theta[i]), add = TRUE,
             col = col.alpha("purple", 0.1))
    for (i in 1:300)
      curve( dbeta2(x, prob = logistic(post$bl_fish[i]), theta = post$theta[i]), add = TRUE,
             col = col.alpha("dodgerblue", 0.2))
    for (i in 1:300)
      curve( dbeta2(x, prob = logistic(post$bd_fish[i]), theta = post$theta[i]), add = TRUE,
             col = col.alpha("orange", 0.15))`

![image](https://cloud.githubusercontent.com/assets/6519519/18320532/2340923c-74df-11e6-9dda-e3b6e834754e.png)

**Comment by rmcelreath** [comment]
The bX_fish parameters are centered on zero, so they end up centered around 0.5 on the logistic scale, as in your second plot. Anyway, doesn't make much sense to plot them without their means.

In your first plot, the bX_fish parameters are referenced as a one-dimensional array, like ba_fish[i]. Since ba_fish is a matrix with 9000 rows and 23 columns (one for each fish), not sure what ba_fish[i] extracts...probably just the first sample in the entire array.

I think instead you want to simulate a random fish from the posterior, so something like:
```
curve( dbeta2(x, prob = logistic(post$b_above[i] + rnorm(1,0,post$sigma_fish[i,1])), theta = post$theta[i]), add = TRUE,  col = col.alpha("black", 0.2))
```
That should hopefully simulate a random fish with the right standard deviation for that effect.

My hunch is that just plotting the means, ignoring the random effects, would be fine.

**Comment by Myfanwy** [comment]
That all makes sense - really sorry for any tedium on your part, but working through it helped me a lot with understanding the structure of the posterior probability.  And yes, I think I'll just go with the fixed effects plot.  But thanks!  For completion, here's the resulting figure from simulating a random fish from the posterior:

![image](https://cloud.githubusercontent.com/assets/6519519/18359908/c9e070a4-75b0-11e6-948f-b6dcf0d688b4.png)
